name: Release and Build Autoglue

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    name: Build Autoglue Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Checkout frontend (autoglue-ui)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: glueops/autoglue-ui  # â† Change this to your frontend repo
          path: autoglue-ui

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"

      - name: Install frontend dependencies
        working-directory: ./autoglue-ui
        run: yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: ./autoglue-ui
        run: yarn build

      - name: Copy frontend dist into backend
        run: |
          rm -rf api/ui
          mkdir -p api/ui
          cp -r autoglue-ui/dist/* api/ui/

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.24"

      - name: Install swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: swag init

      - name: Build binary
        run: go build -o autoglue main.go

      - name: Upload binary
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: autoglue
          path: autoglue

      - name: Log in to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extra short SHA
        id: short-sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/glueops/autoglue:latest
            ghcr.io/glueops/autoglue:${{ steps.short-sha.outputs.sha }}

